### ISSUE TITLE
scale up post cmd failure

### ISSUE THREAD

**Issue by lhenry7** [gianarb/orbiter#34]
I started orbiter with the attached orbiter-stack.yml file, then a service with orbiter flags. Initial scale up and scale down worked, but after scaling down to 1, scale **up** gave error about not being able to scale _**down**_. Used "curl -v -X POST localhost:8081/handle/autoswarm/stage-investor-relations_app/up" for all tests. Log file also attached.

[orbiter-scale-error.zip](https://github.com/gianarb/orbiter/files/1214822/orbiter-scale-error.zip)

**Comment by lhenry7** [comment]
Just wanted to add this as well in case it helps:

[root@ip-10-227-81-34 ~]# curl -v -X GET http://localhost:8081/v1/orbiter/autoscaler
* About to connect() to localhost port 8081 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8081 (#0)
> GET /v1/orbiter/autoscaler HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8081
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Thu, 10 Aug 2017 12:15:59 GMT
< Content-Length: 60
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host localhost left intact
{"data":[{"name":"autoswarm/stage-investor-relations_app"}]}

**Comment by gianarb** [comment]
Hello @lhenry7 thanks for your feedback.
I tried reproducing this issue without success but in the meantime, I fixed an error message and I also change a bit the logic behind that check.

https://github.com/gianarb/orbiter/pull/35

The code is merged. Can you update orbiter and give it a try? Let me know! I will keep trying.

**Comment by gianarb** [comment]
All done @lhenry7 ! I works! I was able to reproduce the bug and it is fixed. Update orbiter and let me know!

You opened a very good PR with a lot of information! Supe

**Comment by lhenry7** [comment]
Yes, works now.  Thanks
