### ISSUE TITLE
Makefile improvements

### ISSUE THREAD

**Issue by fntlnz** [gianarb/orbiter#36]
I think that this issue can be implemented in multiple PRs,

## Echoing the command output is useful

Every single command in the makefile is not echoing the command output, it's very annoying as one of the most important features of Make is that it shows you what it's doing.

## Dockerfile not aligned with Makefile

There are actually two dockerfiles, named `Dockerfile.image` and `Dockerfile.build` .
They can me merged in a single multi staged build Dockerfile and also the image dockerfile has the orbiter command both in `entrypoint` and in `cmd` and this does not work. (no review on that?) Introduced in https://github.com/gianarb/orbiter/pull/30

## PHONY

For example, the `binaries` target should just be an alias to a `bin/orbiter` target without PHONY
Instead `build/docker` should be a PHONY target

**Comment by fntlnz** [comment]
@gianarb PTAL

**Comment by gianarb** [comment]
Hello. I agree. I made it just to support my daily work. You can feel free to improve it as you prefer. I know you will be able to make it inline with other projects like docker and golang. Feel free to submit something. Thanks
