### ISSUE TITLE
Vendor out of sync

### ISSUE THREAD

**Issue by fntlnz** [gianarb/orbiter#38]
The `Gopkg.lock` and `Gopkg.toml` are out of sync.

```
dep status
Lock inputs-digest mismatch. This happens when Gopkg.toml is modified.
Run `dep ensure` to regenerate the inputs-digest.
```

Also seems that there's a `manifest.json` which has another whole set of dependencies and should be deleted since it's used by nothing

**Comment by gianarb** [comment]
I don't remember something like this. I usually don't modify these files. Are you confident enough to open a pr? In other hands I will try to fix it as soon I will have a laptop
