### ISSUE TITLE
VirtualBox host-only adapters error

### ISSUE THREAD

**Issue by afemartin** [gianarb/orbiter#48]
When running `make init` I got the following error:

```
Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": remote error: tls: bad certificate
```
I found some references to this issue here https://github.com/docker/toolbox/issues/346#issuecomment-166968015

Versions:
* OS: Mac OS X 10.11.6
* VirtualBox: 5.1.20
* Docker Machine: 0.11.0

**Comment by gianarb** [comment]
Can you have a look at this comment? https://github.com/docker/toolbox/issues/346#issuecomment-165220856 thanks!! :)
