### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by jwitko** [gianarb/orbiter#55]
Hey @gianarb ,  I am trying to use orbiter for scaling up and down docker containers in my swarm cluster.  I have a little bit of an unusual use-case and I'm unclear on how I might configure orbiter for my use-case.  Is there any way I can reach out to you to have a quick real-time discussion?  I'd be happy to add to the repo documentation with the information I'm able to learn from the conversation.

I'm on:
   skype, "jwitko1"
   freenode irc, "jwitko"
   gchat: jwitko1@gmail.com

**Comment by gianarb** [comment]
I wrote you a message on gchat :) Happy to have a chat
